version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  target-branch: v6
  ignore:
  - dependency-name: System.Text.Json
    versions:
    - 5.0.1
    - 5.0.2
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.9.1
    - 16.9.4
  - dependency-name: Newtonsoft.Json
    versions:
    - 13.0.1
  - dependency-name: protobuf-net
    versions:
    - 3.0.101
  - dependency-name: SimpleExec
    versions:
    - 6.4.0
    - 7.0.0
  - dependency-name: Moq
    versions:
    - 4.16.0
    - 4.16.1
  - dependency-name: coverlet.collector
    versions:
    - 3.0.2
    - 3.0.3
  - dependency-name: Bullseye
    versions:
    - 3.7.0
